Button flip 180
team6749/2024-Crescendo-V2 pull request #46
Opened 2024-03-27 22:35 UTC by 6749computers

2024-03-27 23:03 UTC, 6749computers reviewed
Looks good

-LP

2024-03-28 01:34 UTC, mootw requested changes

2024-03-28 01:34 UTC, mootw commented on src/main/java/frc/robot/subsystems/SwerveDrivebase.java
> +        System.out.println(chassisSpeeds.toString());
```suggestion
```

remove this debug log

2024-03-28 03:36 UTC, mootw approved these changes

2024-03-28 03:36 UTC, merged